removal of template error

diff --git a/roles/avans/templates/student_project_backup.sh.j2 b/roles/avans/templates/student_project_backup.sh.j2
--- a/roles/avans/templates/student_project_backup.sh.j2
+++ b/roles/avans/templates/student_project_backup.sh.j2
@@ -1,84 +1,77 @@
 #!/bin/sh
 
-exit_needed=$(False)
+# See the section "Passphrase notes" for more infos.
+#where it will be stored
+export BORG_REPO={{ hostvars[project.host].backup_user }}@{{ hostvars[project.host].backup_host}}:{{ hostvars[project.host].backup_location}}
+
+export BORG_PASSPHRASE={{.vault_password}}
 
 
-        exit_needed=$(True)
+# initialse backup directory
 
-        # go to directory needed to be backedup
+set -e $BORG_REPO 
 
+# some helpers and error handling:
+info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
+trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM
 
-        # See the section "Passphrase notes" for more infos.
-        #where it will be stored
-        export BORG_REPO={{ hostvars[project.host].backup_user }}@{{ hostvars[project.host].backup_host}}:{{ hostvars[project.host].backup_location}}
+{% for project in atgm_projects %}
+    {% if project.host == ansible_nodename %}
 
-        export BORG_PASSPHRASE={{.vault_password}}
+        #giving information which backup is generated
+        info "Starting backup {{ hostvars[project.host].project_directory }}/{{ project.year }}/{{ project.name }}"
 
+        # Backup the most important directories into an archive named after
+        # the machine this script is currently running on:
 
-        # initialse backup directory
+        borg create \
+            --verbose                                         \
+            --list                                            \
+            --stats                                           \
+            --show-rc                                         \
+            --compression lz4                                 \
+            --exclude-caches                                  \
 
-        set -e $BORG_REPO 
+            #gives the backup name docs-when-of who
+            ::project-{{ project.year }}-{{ project.name }}-$(date "+%Y-%m-%dT%H-%M-%S") \
 
-        # some helpers and error handling:
-        info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
-        trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM
+            #path to directory to be backedup
+            {{ hostvars[project.host].project_directory }}/{{ project.year }}/{{ project.name }}/data_storage
 
-        {% for project in atgm_projects %}
-            {% if project.host == ansible_nodename %}
-        
-                #giving information which backup is generated
-                info "Starting backup {{ hostvars[project.host].project_directory }}/{{ project.year }}/{{ project.name }}"
+        backup_exit=$?
 
-                # Backup the most important directories into an archive named after
-                # the machine this script is currently running on:
+        info "Pruning repository project-{{ project.year }}-{{ project.name }} "
 
-                borg create \
-                    --verbose                                         \
-                    --list                                            \
-                    --stats                                           \
-                    --show-rc                                         \
-                    --compression lz4                                 \
-                    --exclude-caches                                  \
+        # Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
+        # archives of THIS machine. The '{hostname}-' prefix is very important to
+        # limit prune's operation to this machine's archives and not apply to
+        # other machines' archives also:
 
-                    #gives the backup name docs-when-of who
-                    ::project-{{ project.year }}-{{ project.name }}-$(date "+%Y-%m-%dT%H-%M-%S") \
+        borg prune                 \
+            --remote-path=$BORG_REPO     \
+            --list                 \
+            --prefix 'project-{{ project.year }}-{{ project.name }}' \
+            --show-rc              \
+            #NA because we only do weekly
+            --keep-daily    1      \
+            #should be automatic as our projects increases aka we keep the number of amount projects per week
+            --keep-weekly   1     \
+            # we keep number of projects for 4 weeks?
+            --keep-monthly  4   
 
-                    #path to directory to be backedup
-                    {{ hostvars[project.host].project_directory }}/{{ project.year }}/{{ project.name }}/data_storage
+        prune_exit=$?
+    {% endif %}
+{% endfor %}    
 
-                backup_exit=$?
+# use highest exit code as global exit code
+global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
 
-                info "Pruning repository project-{{ project.year }}-{{ project.name }} "
+if [ ${global_exit} -eq 0 ]; then
+    info "Backup and Prune finished successfully"
+elif [ ${global_exit} -eq 1 ]; then
+    info "Backup and/or Prune finished with warnings"
+else
+    info "Backup and/or Prune finished with errors"
+fi
 
-                # Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
-                # archives of THIS machine. The '{hostname}-' prefix is very important to
-                # limit prune's operation to this machine's archives and not apply to
-                # other machines' archives also:
-
-                borg prune                 \
-                    --remote-path=$BORG_REPO     \
-                    --list                 \
-                    --prefix 'project-{{ project.year }}-{{ project.name }}' \
-                    --show-rc              \
-                    #NA because we only do weekly
-                    --keep-daily    1      \
-                    #should be automatic as our projects increases aka we keep the number of amount projects per week
-                    --keep-weekly   1     \
-                    # we keep number of projects for 4 weeks?
-                    --keep-monthly  4   
-
-                prune_exit=$?
-            {% endif %}
-        {% endfor %}    
-        # use highest exit code as global exit code
-        global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
-
-        if [ ${global_exit} -eq 0 ]; then
-            info "Backup and Prune finished successfully"
-        elif [ ${global_exit} -eq 1 ]; then
-            info "Backup and/or Prune finished with warnings"
-        else
-            info "Backup and/or Prune finished with errors"
-        fi
-
-        exit ${global_exit}
+exit ${global_exit}
