adding surfsara

diff --git a/roles/Cocalc_backup/templates/Cocalc_backup.sh.j2 b/roles/Cocalc_backup/templates/Cocalc_backup.sh.j2
--- a/roles/Cocalc_backup/templates/Cocalc_backup.sh.j2
+++ b/roles/Cocalc_backup/templates/Cocalc_backup.sh.j2
@@ -44,7 +44,7 @@ do
   
   backup_exit=$?
   
-  info "Pruning repository of project-${tmp_id} "
+  info "Pruning repository of project $tmp_id"
   
   # Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
   # archives of THIS machine. The '{hostname}-' prefix is very important to
@@ -70,5 +70,69 @@ info "setting up sshfs connection!"
 sshfs -o  IdentityFile=/home/{{backup_user}}/.ssh/{{encrypted_ssh_private_key_archive}} {{backup_archive_usr_1}}@{{backup_archive_addres_1}}:{{back_up_archive_path_1}} /home/{{backup_user}}/archive_mountpoint
 export BORG_REPO=/home/{{backup_user}}/archive_mountpoint
 
+while IFS= read -r line
+do
+  echo "$line"
+  identifier=$(echo $line | cut -d " " -f 1)
+  tmp_id=$(echo $line | cut -d " " -f2-)
+  tmp_id=${tmp_id// /_}
+
+
+        #giving information which backup is generated
+        info  "Starting backup {{ hostvars[ansible_nodename].teacher_directory }}/research/{{ project.name }} on archive"
+
+        # Backup the most important directories into an archive named after
+        # the machine this script is currently running on:
+
+        borg create \
+            --verbose                                         \
+            --stats                                           \
+            --show-rc                                         \
+            --compression lz4                                 \
+            --exclude-caches                                  \
+        $BORG_REPO::project-${tmp_id}-$(date "+%Y-%m-%dT%H-%M-%S") \
+        {{ cocalc_data_dir }}/${identifier}
+
+        backup_exit=$?
+
+        info "Pruning repository of research project $tmp_id "
+
+        # Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
+        # archives of THIS machine. The '{hostname}-' prefix is very important to
+        # limit prune's operation to this machine's archives and not apply to
+        # other machines' archives also:
+
+        borg prune --list --prefix 'Research_project-${tmp_id}' --show-rc --keep-daily=1 --keep-weekly=1 --keep-monthly=3 $BORG_REPO  
+
+        prune_exit=$?
+
+
+#Find total number of Archives
+N_archives=$(borg list $BORG_REPO | wc -l)
+info "Number of Archives on {{ backup_archive_addres_1 }} \t $N_archives"
+
+#get total size archives
+size_archive=$(borg info | grep "All archives")
+info "Size archives on {{ backup_archive_addres_1 }} $size_archive"
+
+info "closing up sshfs connection!"
+
+fusermount -u /home/{{backup_user}}/archive_mountpoint
+rmdir /home/{{backup_user}}/archive_mountpoint
+
+
+# use highest exit code as global exit code
+
+global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
+
+if [ ${global_exit} -eq 0 ]; then
+    info "Backup and Prune finished successfully"
+elif [ ${global_exit} -eq 1 ]; then
+    info "Backup and/or Prune finished with warnings"
+else
+    info "Backup and/or Prune finished with errors"
+fi
+
+exit ${global_exit}
 
 rm cocalc_db.tmp
